apiVersion: dsdf.7sg.ai/v1
kind: DataSourceDefinition
metadata:
  name: taxi-data
  tags:
    service: spark
    purpose: curated-dataset
    env: prod
home:
  tdfRef: azure-east
connection:
  type: warehouse
  provider: azure-synapse-spark
  endpoint: https://<synapse-workspace>.dev.azuresynapse.net
  resource: <spark-pool-name>
  format: delta
  notes: Curated Taxi Data produced by Synapse Spark from Downloaded Taxi Data; replicated
    to Crusoe VAST for consumption.
  source:
    dsdfRef: dsdf/downloaded-taxi-data.dsdf.202602191817.yaml
    description: Raw taxi trip parquet staged in ADLS Gen2.
  stagingStore:
    type: object-store
    provider: adls-gen2
    endpoint: abfss://<container>@<storage-account>.dfs.core.windows.net/
    resource: taxi-curated/
auth:
  method: azure-managed-identity
  secretRefs: []
secrets:
  provider: inherit
  inheritFromWdf: true
  secretRefs: []
replication:
  enabled: false
  method: streaming
  targets:
  - tdfRef: crusoe
    destination:
      type: object-store
      provider: s3
      endpoint: https://<vast-s3-endpoint>
      resource: s3://<vast-bucket>/taxi-curated/
      format: delta
    transport:
      type: kafka
      serviceRefs:
        source:
          tdfRef: azure-east
          service: kafka-bridge
        target:
          tdfRef: crusoe
          service: kafka-bridge
      topic: taxi-data.delta
      security:
        mode: sasl_ssl
        authRef: kafka-credentials
